### ISSUE TITLE
BVC-74 :: SQL Prepare Without Close Memory Leak

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-shield-server#142]
"I see 3 locations in the server where prepare is used without a close:

https://github.com/cds-snc/covid-shield-server/blob/master/pkg/persistence/queries.go#L76

https://github.com/cds-snc/covid-shield-server/blob/master/pkg/persistence/queries.go#L117

https://github.com/cds-snc/covid-shield-server/blob/master/pkg/persistence/queries.go#L224"

https://golang.org/pkg/database/sql/#DB.Prepare

**Comment by maxneuvians** [comment]
Assuming this statement is true:

`The statements prepared for a transaction by calling the transaction's Prepare or Stmt methods are closed by the call to Commit or Rollback.`

Source: https://golang.org/pkg/database/sql/#Tx

Is this actually an issue?

**Comment by obrien-j** [comment]
LGTM. Marking as closed. I'll upstream this to CCCS.
