### ISSUE TITLE
BVC-71 :: TOUTOC bug in new-key-claim endpoint

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-shield-server#147]
Similar problem to #140 but on new-key-claim path.

"
A solution to this vulnerability would be to check and add the one-time-code entry in a single SQL command. If the intented functionality of this endpoint is to ensure unique hash per one-time-code, developers may consider using the the sql REPLACE command for hashID requests."

Alternatively, it would probably make sense to have a unique constraint on the hashID field as well, which, would fix this, and any other potential bug we may have lurking.

**Comment by maxneuvians** [comment]
Tried the UNIQUE constraint and realized NULL or "" has to be unique too ;)
