### ISSUE TITLE
[For Discussion] Lack of CORS implementation

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-shield-server#33]
"There are comments to this in the code, but the CORS headers are hard coded as * for now.  I would prefer to see that set from a config file or environment variable."

https://github.com/cds-snc/covid-shield-server/blob/d7efce28ea20ce1217a7e67adf0f948461c2ba62/pkg/server/keyclaim.go#L40

Current implementation of CORS is stubbed out with a TODO. Adding this issue to ensure we close this out in accordance with best practices, and also drop in observatory scan results into here if so desired.

**Comment by whytoe** [comment]
@obrien-j could this be added to the config.yaml configuration as a variable?
