### ISSUE TITLE
SRV-H-1.11: Cloudfront compression

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/covid-shield-server#69]
**Finding**:
CloudFront compression is not enabled

**Recommendation**:
Enabling compression can improve user experience and reduce cost

**Comment by burke** [comment]
I'm not sure this is necessary: the only files sent are zip files, which are already compressed, and tiny JSON blobs which are unlikely to be more than 1–2 packets anyway.

Doesn't seem harmful though 🤷
