### ISSUE TITLE
SRV-H-1.13: Retrieval WAF

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/covid-shield-server#71]
**Finding**:
Retrieval service lacks WAF

**Recommendation**:
Retrieval service only presents GET /retrieve so at the moment a WAF isn't very important, but for parity with the Submission service and for future-proofing, attaching a WAF to the Retrieval service ALB (or perhaps the CloudFront Distribution) could be worthwhile

**Comment by obrien-j** [comment]
Would love to understand the cost implications of this, given this will be a relatively heavy query path. Will flag this one to AWS for a 2nd set of eyes.

**Comment by jamesarmitage** [comment]
@obrien-j I'll make sure you have full sight on this.  Note that "AWS WAF is included with AWS Shield Advanced at no extra cost."

https://docs.aws.amazon.com/waf/latest/developerguide/ddos-overview.html#ddos-advanced

**Comment by maxneuvians** [comment]
It might be nice to block URLs that don't fit the retrieval URL schema:

https://github.com/cds-snc/covid-shield-server/blob/master/pkg/server/retrieve.go#L36

and

https://github.com/cds-snc/covid-shield-server/blob/master/pkg/server/config.go#L22

**Comment by whytoe** [comment]
This https://github.com/cds-snc/covid-shield-server/blob/master/pkg/server/services.go#L26-L27 is currently being used to verify Continuous Deployment(CD) step was successful from external services.

- Unable to use external website checking services like happyapps or R-U-ON (ping)
- Unable to verify deployment from GitHub pipeline as the CD test would only be accessible internally (versions)

**Comment by maxneuvians** [comment]
Sorry I meant the WAF should block all but those URLs

**Comment by whytoe** [comment]
Talked with @stonith and based on his WAFv2 work, he will take this item on

**Comment by maxneuvians** [comment]
We need to set up a WAF for Cloudfront and the retreival ALB just to monitor the logs if we don't set up rules
