### ISSUE TITLE
SRV-H-2.1: Alarms

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/covid-shield-server#74]
**Finding**:
Deployment lacks alarming

**Recommendation**: 
Appropriate thresholds should be placed on KPIs for alarming

**Comment by maxneuvians** [comment]
Partially addressed in #42 and #45 but needs more work.

**Comment by whytoe** [comment]
@maxneuvians I can complete this
Do you have a list of alarms you want implemented?
