### ISSUE TITLE
SRV-H-2.6: ECS Autoscaling

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/covid-shield-server#79]
**Finding**:
ECS services are fixed at two replicas

**Recommendation**:
Enable ECS autoscaling

**Comment by maxneuvians** [comment]
Unfortunately did not work - scaled the workloads to 0 and took them offline. It looks like we need to define alarms that trigger autoscaling actions: https://medium.com/@bradford_hamilton/deploying-containers-on-amazons-ecs-using-fargate-and-terraform-part-2-2e6f6a3a957f

**Comment by jorgehrn** [comment]
As @maxneuvians mentioned, in the merged code there isn't a cloudwatch metric alarm that trigger the escalation process. ECS service support several scaling strategies https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-auto-scaling.html. The example in medium blog use step_scaling, but maybe you should review target tracking policy (target_tracking_scaling_policy_configuration in Terraform)

**Comment by whytoe** [comment]
I have another branch that is pushed with the fixes , maybe someone can verify the deployment as I have no access to your AWS infrastructure
