### ISSUE TITLE
Migrate Fargate to platform version 1.4

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/covid-shield-server#90]
Currently `Latest` equates to 1.3, whereas we would like to use some of the features found in 1.4 (https://aws.amazon.com/about-aws/whats-new/2020/04/aws-fargate-launches-platform-version-14/). 

Required change is to:

https://www.terraform.io/docs/providers/aws/r/ecs_service.html#platform_version

**Comment by whytoe** [comment]
AWS documentation states it should default to Latest

`platform_version - (Optional) The platform version on which to run your service. Only applicable for launch_type set to FARGATE. Defaults to LATEST. More information about Fargate platform versions can be found in the AWS ECS User Guide. `

**Comment by obrien-j** [comment]
"Fargate tasks now support the CAP_SYS_PTRACE Linux capability"++
