### ISSUE TITLE
VA80 - KeyClaim (OneTimeCode) API requires different protection then OTC verification/key submission API's

### ISSUE THREAD

**Issue by caitlintuba** [cds-snc/covid-shield-server#99]
Service has two different user groups
The keyclaim service implements functionality that would be used by health care providers, as well as the general public.  These user groups are vastly different and by implementing the functionality in a shared service like this you are exposing the new-key-claim method to a wider audience of potentially malicious users. 

REC-3 SEPARATE FUNCTIONALITY: The new-key-claim and claim-key methods should be split into separate services so that the audience for the new-key-claim method can be limited.

_This came from the vulnerability analysis; originally Loudmouth Recommendation 3; was marked as low priority by security assessment team_

**Comment by whytoe** [comment]
Is this a duplicate of #34

**Comment by obrien-j** [comment]
Implement path/IP based WAF acl's
* Set default 'block' rule on "/new-key-claim" paths
* Create IP Set (IP's to be provided by P/T's at time of integration for allowlisting)
* Create allow rule on PT_IPSET & path==starts_with("/new-key-clam/") ish.

**Comment by maxneuvians** [comment]
We still need to set up the IP block sets for this

**Comment by maxneuvians** [comment]
Closed in #177
